stats-server:
  url: ${STATS_SERVER_URL}

spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
  sql:
    init:
      mode: always
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${EWM_DATASOURCE_URL}
    # url: jdbc:postgresql://localhost:5432/exploreWithMe
    username: root
    password: root

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE